name: Deploy

on:
  workflow_call:
    # No secrets passed by the caller
    inputs: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout calling repo
        uses: actions/checkout@v3

      - name: Read values from package.json
        id: pkg
        run: |
          echo "PKG_NAME=$(jq -r '.name' package.json)" >> $GITHUB_OUTPUT
          echo "PREVIEW_PORT=$(jq -r '.previewPort' package.json)" >> $GITHUB_OUTPUT

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          command_timeout: 600s
          script: |
            export NVM_DIR=~/.nvm
            . ~/.nvm/nvm.sh
            cd websites/${{ steps.pkg.outputs.PKG_NAME }}

            echo "Checking out main branch..."
            if ! git checkout main; then
              echo "::error::Failed to checkout 'main'"
              exit 1
            fi

            git reset --hard
            git clean -fd

            if ! git pull --rebase; then
              echo "::error::Git pull failed"
              exit 1
            fi

            npm install
            npm run build:preview

            pm2 delete ${{ steps.pkg.outputs.PKG_NAME }} || true
            MODE=preview PORT=${{ steps.pkg.outputs.PREVIEW_PORT }} pm2 start npm --name ${{ steps.pkg.outputs.PKG_NAME }} -- run start
